[package]
name = "coin-eos"
version = "0.1.0"
authors = ["joe <xielamenla@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../../common"}
mq = {path = "../../mq"}
bitcoin_hashes = "0.7"
hex = "0.3.2"
bitcoin = "0.19.1"
bytes = "0.4.8"
